### ISSUE TITLE
 Deploy site to Pages - build - install Noll 失败

### ISSUE THREAD

**Issue by xxnuo** [NollGo/Noll#45]
![图片](https://github.com/NollGo/Noll/assets/54252779/0b29c038-6fdd-4cf6-8a29-a1f34ee2ec78)

**Comment by xxnuo** [comment]
修改 `noll.yml` 后 `Install Noll` 正常了
```yml
      - name: Build Noll
        run: |
          cd ./Noll
          go mod tidy
          go build --ldflags="-w -s"
          chmod 775 ./io.github.nollgo
```

但 `Build Site` 又会出错

```log
Run repository=xxnuo/NollAction
  repository=xxnuo/NollAction
  repositoryName=$(basename "$repository")
  pagesPath="./"
  baseURL="/$repositoryName"
  gamID=""
  echo "ARGS: xxnuo, $repositoryName, ***, $pagesPath, $baseURL, $gamID,"
  if [ -z "$gamID" ]; then
    ./Noll/io.github.nollgo -owner xxnuo -name $repositoryName  -token *** -pages "$pagesPath" -baseURL "$baseURL"
  else
  ./Noll/io.github.nollgo -owner xxnuo -name $repositoryName  -token *** -pages "$pagesPath" -baseURL "$baseURL" -gamID "$gamID"
  fi
  ls -a -lh
  shell: /usr/bin/bash -e {0}
ARGS: xxnuo, NollAction, ***, ./, /NollAction, ,
Usage of ./Noll/io.github.nollgo:
  -baseURL value
    	Web site base url
  -config string
    	Configuration file path.
  -debug value
    	Debug mode if true
  -debugMod value
    	Debug mode: auto, manual. Automatic debugging mode and manual debugging mode
  -export value
    	Export all Discussions to markdown, Value is the export directory
  -gamID value
    	Google Analytics Measurement id, Defaults to empty to not load the Google Analytics script
  -name value
    	Github repository name
  -newSite value
    	Generate theme, Defaults to false
  -owner value
    	Github repository owner
  -pages value
    	Your github pages repository name, If None, defaults to the repository where the discussion resides
  -themeDir value
    	Filesystem path to themes directory, Defaults to embed assets/theme
  -token value
    	Github authorization token (see https://docs.github.com/zh/graphql/guides/forming-calls-with-graphql)
Start build noll siteweb
Start get xxnuo/NollAction repository
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.getGemoji(0xc0001a4030, 0xf, 0x7fffc8c2ce6a, 0xa)
	/mnt/d/r/dev/_work/NollAction/NollAction/Noll/github.go:16 +0x89
main.getRepository(0x7fffc8c2ce5e, 0x5, 0x7fffc8c2ce6a, 0xa, 0x7fffc8c2ce7c, 0x28, 0xffffffffffffffff, 0x7fffc8c2ceb8, 0xb)
	/mnt/d/r/dev/_work/NollAction/NollAction/Noll/github.go:41 +0x373
main.main.func1(...)
	/mnt/d/r/dev/_work/NollAction/NollAction/Noll/main.go:68
main.main()
	/mnt/d/r/dev/_work/NollAction/NollAction/Noll/main.go:90 +0x437
Error: Process completed with exit code 2.
```

**Comment by excing** [comment]
Github Actions 升级造成的兼容性问题，已修复，更新 `NollAction` 即可
